apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oracle21c 
  namespace: oracle-namespace
  labels:
    app: database
    version: 21.3.0.0
spec:
  serviceName: "oracle21c"
  replicas: 1
  selector:
    matchLabels:
      app: database
      version: 21.3.0.0
  template:
    metadata:
      name: oracle21c
      labels:
        app: database
        version: 21.3.0.0
    spec:
      securityContext:
        fsGroup: 54321
      volumes:
         - name: dshm
           emptyDir:
             medium: Memory
      imagePullSecrets:
       - name: regcred
      containers:
        - name: oracle21c
          image: container-registry.oracle.com/database/enterprise:latest
          command:
          - /opt/oracle/runOracle.sh
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 4Gi
          ports:
            - name: listener
              containerPort: 1521
              hostPort: 1521
            - name: oemexpress
              containerPort: 5500
              hostPort: 5500
          volumeMounts:
            - name: dshm
              mountPath: "/dev/shm"
            - name: ora-data213
              mountPath: "/opt/oracle/oradata"
            - name: ora-setup213
              mountPath: "/opt/oracle/scripts/setup"
            - name: ora-startup213
              mountPath: "/opt/oracle/scripts/startup"
          env:
            - name: ORACLE_SID
              valueFrom:
                configMapKeyRef:
                  name: oradb #Read from a configmap called oradb
                  key: ORACLE_SID #Read the key call ORACLE_SID
            - name: ORACLE_PDB
              valueFrom:
                configMapKeyRef:
                  name: oradb #Read from a configmap called oradb
                  key: ORACLE_PDB #Read the key call ORACLE_PDB
            - name: ORACLE_PWD
              valueFrom:
                configMapKeyRef:
                  name: oradb #Read from a configmap called oradb
                  key: ORACLE_PWD #Read the key call ORACLE_PWD
            - name: ENABLE_ARCHIVELOG
              valueFrom:
                configMapKeyRef:
                  name: oradb #Read from a configmap called oradb
                  key: ENABLE_ARCHIVELOG #Read the key call ENABLE_ARCHIVELOG
            - name: ORACLE_CHARACTERSET
              valueFrom:
                configMapKeyRef:
                  name: oradb #Read from a configmap called oradb
                  key: ORACLE_CHARACTERSET #Read the key call ORACLE_CHARACTERSET
            - name: ORACLE_EDITION
              valueFrom:
                configMapKeyRef:
                  name: oradb #Read from a configmap called oradb
                  key: ORACLE_EDITION #Read the key call ORACLE_EDITION
  volumeClaimTemplates:
  - metadata:
      name: ora-startup213 
    spec:
      storageClassName: px-ora-sc
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: ora-setup213
    spec:
      storageClassName: px-ora-sc
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: ora-data213
    spec:
      storageClassName: px-ora-sc
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: oracle21c
  namespace: oracle-namespace
  labels:
    app: database
    version: 21.3.0.0
spec:
  selector:
    app: database
    version: 21.3.0.0
  type: NodePort
  ports:
  - name: listener
    protocol: TCP
    port: 1521
    targetPort: 1521
  - name: oemexpress
    protocol: TCP
    port: 5500
    targetPort: 5500
